const STORAGE_KEY='meal-planner-v3';
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const MEALS=['breakfast','lunch','dinner'];
const CATEGORIES=['Produce','Meat & Fish','Dairy & Eggs','Cupboard','Frozen','Bakery','Drinks','Other'];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
const demoRecipe={id:uid(),name:'Spaghetti Bolognese',category:'Dinner',basePortions:4,prepMinutes:10,cookMinutes:35,ingredients:[{quantity:500,unit:'g',name:'beef mince',category:'Meat & Fish'},{quantity:1,unit:'',name:'onion',category:'Produce'},{quantity:2,unit:'× 400 g',name:'chopped tomatoes',category:'Cupboard'},{quantity:400,unit:'g',name:'spaghetti',category:'Cupboard'}],instructions:'Brown the mince and onion. Add tomatoes and simmer. Cook spaghetti and serve.'};
function blankMeal(){return{recipeId:'',eat:2,cook:0,fromFreezer:0}}
function initialState(){let plan={};DAYS.forEach(d=>{plan[d]={};MEALS.forEach(m=>plan[d][m]=blankMeal())});return{householdSize:2,recipes:[demoRecipe],plan,freezer:[],shopping:{}}}
let state=load();
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return saved||initialState()}catch{return initialState()}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function notify(message){const el=document.querySelector('#notice');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function recipe(id){return state.recipes.find(r=>r.id===id)}
function render(){renderPlanner();renderRecipes();renderFreezer();renderShopping()}
function renderPlanner(){const grid=document.querySelector('#planner-grid');grid.innerHTML=DAYS.map(day=>`<div class="day-column"><h3>${day}</h3>${MEALS.map(meal=>{const p=state.plan[day][meal];const r=recipe(p.recipeId);const fresh=Math.max(0,Number(p.cook)||0);const surplus=Math.max(0,fresh-(Number(p.eat)||0));return `<article class="meal-card"><h4>${meal}</h4><select data-day="${day}" data-meal="${meal}" class="recipe-select"><option value="">No recipe</option>${state.recipes.map(x=>`<option value="${x.id}" ${x.id===p.recipeId?'selected':''}>${escapeHtml(x.name)}</option>`).join('')}</select><div class="meal-fields"><label>Eat<input type="number" min="0" data-field="eat" data-day="${day}" data-meal="${meal}" value="${p.eat}"></label><label>Cook<input type="number" min="0" data-field="cook" data-day="${day}" data-meal="${meal}" value="${p.cook}"></label><label>Freezer<input type="number" min="0" data-field="fromFreezer" data-day="${day}" data-meal="${meal}" value="${p.fromFreezer}"></label></div>${r?`<p class="metric">Fresh surplus: <strong>${surplus}</strong><br>Fresh ingredients: <strong>${fresh}</strong> portions</p>`:''}</article>`}).join('')}</div>`).join('');
 grid.querySelectorAll('select,input').forEach(el=>el.addEventListener('change',()=>{const p=state.plan[el.dataset.day][el.dataset.meal];if(el.classList.contains('recipe-select'))p.recipeId=el.value;else p[el.dataset.field]=Math.max(0,Number(el.value)||0);save();render();notify('Plan updated') }));document.querySelector('#household-size').value=state.householdSize}
function renderRecipes(){document.querySelector('#recipe-list').innerHTML=state.recipes.length?state.recipes.map(r=>`<article class="recipe-card"><div><h3>${escapeHtml(r.name)}</h3><span class="muted">${escapeHtml(r.category||'Uncategorised')} · base ${r.basePortions} portions · ${r.ingredients.length} ingredients</span></div><div class="recipe-actions"><button class="button secondary" data-edit="${r.id}">Edit</button><button class="button secondary" data-delete="${r.id}">Delete</button></div></article>`).join(''):'<p class="help-text">No recipes yet. Add your first recipe.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openRecipe(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this recipe? Planned meals will become blank.')){state.recipes=state.recipes.filter(r=>r.id!==b.dataset.delete);Object.values(state.plan).forEach(day=>Object.values(day).forEach(p=>{if(p.recipeId===b.dataset.delete)p.recipeId=''}));save();render()}})}
function openRecipe(id=''){const r=recipe(id);document.querySelector('#recipe-form').classList.remove('hidden');document.querySelector('#recipe-form-title').textContent=r?'Edit recipe':'Add recipe';document.querySelector('#recipe-id').value=id;document.querySelector('#recipe-name').value=r?.name||'';document.querySelector('#recipe-category').value=r?.category||'';document.querySelector('#recipe-portions').value=r?.basePortions||4;document.querySelector('#recipe-prep').value=r?.prepMinutes||0;document.querySelector('#recipe-cook-time').value=r?.cookMinutes||0;document.querySelector('#recipe-ingredients').value=r?.ingredients.map(i=>`${i.quantity} | ${i.unit} | ${i.name} | ${i.category}`).join('\n')||'';document.querySelector('#recipe-instructions').value=r?.instructions||'';document.querySelector('#recipe-name').focus()}
function parseIngredients(text){return text.split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const [quantity='',unit='',name='',category='Other']=line.split('|').map(x=>x.trim());return{quantity:Number(quantity)||0,unit,name,category:CATEGORIES.includes(category)?category:'Other'}}).filter(i=>i.name)}
function renderFreezer(){const balances={};state.freezer.forEach(x=>balances[x.recipeId]=(balances[x.recipeId]||0)+x.portions);Object.values(state.plan).forEach(day=>Object.values(day).forEach(p=>{if(p.recipeId)balances[p.recipeId]=(balances[p.recipeId]||0)+Math.max(0,(Number(p.cook)||0)-(Number(p.eat)||0))-(Number(p.fromFreezer)||0)}));const entries=Object.entries(balances).filter(([,n])=>n>0);document.querySelector('#freezer-list').innerHTML=entries.length?entries.map(([id,n])=>`<article class="freezer-card"><div><strong>${escapeHtml(recipe(id)?.name||'Unknown recipe')}</strong><div class="muted">Calculated stock from batch cooking and planned freezer use</div></div><strong>${n} portion${n===1?'':'s'}</strong></article>`).join(''):'<p class="help-text">No frozen portions currently available. Batch-cook a meal to build freezer stock.</p>'}
function shoppingItems(){const result={};Object.values(state.plan).forEach(day=>Object.values(day).forEach(p=>{const r=recipe(p.recipeId), portions=Math.max(0,Number(p.cook)||0);if(!r||!portions)return;const scale=portions/r.basePortions;r.ingredients.forEach(i=>{const key=`${i.category}|${i.name.toLowerCase()}|${i.unit}`;if(!result[key])result[key]={name:i.name,unit:i.unit,category:i.category,quantity:0};result[key].quantity+=i.quantity*scale})}));return result}
function renderShopping(){const generated=shoppingItems();const items={...generated,...state.shopping};const groups={};Object.values(items).forEach(i=>(groups[i.category||'Other']??=[]).push(i));document.querySelector('#shopping-list').innerHTML=Object.keys(groups).length?Object.entries(groups).map(([cat,items])=>`<section class="shopping-group"><h3>${cat}</h3>${items.map(i=>{const key=i.id||`${i.category}|${i.name.toLowerCase()}|${i.unit}`;return `<label class="shopping-item ${i.checked?'checked':''}"><input type="checkbox" data-shopping="${escapeHtml(key)}" ${i.checked?'checked':''}><span>${formatQuantity(i.quantity)} ${escapeHtml(i.unit||'')} ${escapeHtml(i.name)}</span></label>`}).join('')}</section>`).join(''):'<p class="help-text">Your shopping list is empty. Select recipes and add fresh Cook portions.</p>';document.querySelectorAll('[data-shopping]').forEach(c=>c.onchange=()=>{const item=state.shopping[c.dataset.shopping];if(item){item.checked=c.checked;save();renderShopping()}})}
function formatQuantity(n){return Number.isInteger(n)?n:Number(n.toFixed(2))}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.querySelector('#'+tab.dataset.view+'-view').classList.add('active')});document.querySelector('#household-size').onchange=e=>{state.householdSize=Math.max(1,Number(e.target.value)||2);Object.values(state.plan).forEach(day=>Object.values(day).forEach(p=>{if(p.eat===2)p.eat=state.householdSize}));save();render()};document.querySelector('#add-recipe-button').onclick=()=>openRecipe();['cancel-recipe','cancel-recipe-2'].forEach(id=>document.querySelector('#'+id).onclick=()=>document.querySelector('#recipe-form').classList.add('hidden'));document.querySelector('#recipe-form').onsubmit=e=>{e.preventDefault();const id=document.querySelector('#recipe-id').value;const data={id:id||uid(),name:document.querySelector('#recipe-name').value.trim(),category:document.querySelector('#recipe-category').value.trim(),basePortions:Math.max(1,Number(document.querySelector('#recipe-portions').value)||1),prepMinutes:Number(document.querySelector('#recipe-prep').value)||0,cookMinutes:Number(document.querySelector('#recipe-cook-time').value)||0,ingredients:parseIngredients(document.querySelector('#recipe-ingredients').value),instructions:document.querySelector('#recipe-instructions').value.trim()};const index=state.recipes.findIndex(r=>r.id===id);if(index>=0)state.recipes[index]=data;else state.recipes.push(data);save();document.querySelector('#recipe-form').classList.add('hidden');render();notify('Recipe saved')};document.querySelector('#manual-item-form').onsubmit=e=>{e.preventDefault();const name=document.querySelector('#manual-item').value.trim();const id='manual-'+uid();state.shopping[id]={id,name,quantity:1,unit:'',category:document.querySelector('#manual-category').value,checked:false};save();e.target.reset();renderShopping()};document.querySelector('#clear-checked').onclick=()=>{Object.keys(state.shopping).forEach(k=>{if(state.shopping[k].checked)delete state.shopping[k]});save();renderShopping()};document.querySelector('#export-button').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='meal-planner-backup.json';a.click();URL.revokeObjectURL(a.href)};document.querySelector('#import-input').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!imported.recipes||!imported.plan)throw Error();state=imported;save();render();notify('Backup imported')}catch{alert('That file is not a valid meal planner backup.')}};reader.readAsText(file)};document.querySelector('#reset-data').onclick=()=>{if(confirm('Reset all local data to the demo?')){state=initialState();save();render()}};render();
